(let ([x (and (> 3 2) (< 1 6))])
	(if x
		(- (+ (let ([y (if (> (read) 1) 10 0)]) (+ y 5))
				(+ (let ([y (if (> (read) 1) 10 0)]) (+ y 5))
					(+ (let ([y (if (> (read) 1) 10 0)]) (+ y 5))
						(+ (let ([y (if (> (read) 1) 10 0)]) (+ y 5))
							(+ (let ([y (if (> (read) 1) 10 0)]) (+ y 5))
								(+ (let ([y (if (> (read) 1) 10 0)]) (+ y 5))
									(+ (let ([y (if (> (read) 1) 10 0)]) (+ y 5))
										(read))))))))
			23)
		10))