(let ([x (and (> 3 2) (< 1 6))])
	(if x
		(- (let ([y 10])
			(+ y (let ([y 10])
				(+ y (let ([y 10])
					(+ y (let ([y 10])
						(+ y (let ([y 10])
							(+ y (let ([y 10])
								(+ y (let ([y 10])
									(+ y (let ([y 10])
										y)))))))))))))))
			38)
		10))