(let ([a1 1])
  (let ([a2 1])
    (let ([a3 1])
      (let ([a4 1])
        (let ([a5 1])
          (let ([a6 1])
            (let ([a7 1])
              (let ([a8 1])
                (let ([a9 1])
                  (let ([a10 1])
                    (let ([a11 1])
                      (let ([a12 1])
                        (let ([a13 1])
                          (let ([a14 1])
                            (let ([a15 1])
                              (let ([a16 1])
                                (let ([a17 1])
                                  (let ([a18 1])
                                    (let ([a19 1])
                                      (let ([a20 1])
                                        (let ([a21 1])
                                          (let ([a22 #f])
                                            (let ([a23 (eq? a19 a21)])
                                              (let ([a24 (> a17 a18)])
                                                (let ([a25 (< a15 a16)])
                                                  (if (< a1 a2)
                                                    (if (< a3 a4)
                                                      (+ a5 (+ a6 (+ a7 a8)))
                                                      a13
                                                      )
                                                    (if (< a5 a6)
                                                      (+ a9 (+ a10 (+ a11 a12)))
                                                      (if a25
                                                        (if a24
                                                          a1
                                                          a2)
                                                        (if a23
                                                          a3
                                                          a4))
                                                      )
                                                    )
                                                  )))))))))))))))))))))))))
